authors = ["Justin Dressel <dressel@chapman.edu>"]
name = "QuantumBayesian"
uuid = "ab2bcadc-a38f-11e8-0d90-f727af0ac06c"
version = "0.3.0"

[deps]
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
